#ifndef SERIAL_INTERNALS_H
#define SERIAL_INTERNALS_H

#include <garn/types.h>

#define COM_PORT 0x3F8

#define COM_DATA COM_PORT
#define COM_INT COM_PORT+1
#define COM_DIVISOR_LSB COM_PORT
#define COM_DIVISOR_MSB COM_PORT+1
#define COM_FIFO_CTRL COM_PORT+2
#define COM_LINE_CONTROL COM_PORT+3
#define COM_MODEM_CTRL COM_PORT+4
#define COM_LINE_STATUS COM_PORT+5
#define COM_SCRATCH COM_PORT+7

int serial_init();

#endif //SERIAL_INTERNALS_H
